export const CHANGE_BASE_VALUE = "CHANGE_BASE_VALUE";
export const CHANGE_CATEGORY_ID = "CHANGE_CATEGORY_ID";
export const CHANGE_UNIT_LEFT = "CHANGE_UNIT_LEFT";
export const CHANGE_UNIT_RIGHT = "CHANGE_UNIT_RIGHT";